function(showInitialProjectInfos)
    message(STATUS "========================================================")
    message(STATUS "CMAKE_SIZEOF_VOID_P : ${CMAKE_SIZEOF_VOID_P}")
    message(STATUS "CMAKE_SYSTEM_NAME : ${CMAKE_SYSTEM_NAME} | CMAKE_SYSTEM_VERSION : ${CMAKE_SYSTEM_VERSION} ${BITS}bits")
    message(STATUS "Project name : ${PROJECT_NAME} | Version : ${PROJECT_VERSION}")
    message(STATUS "PROJECT_SOURCE_DIR : ${PROJECT_SOURCE_DIR}")
    message(STATUS "PROJECT_BINARY_DIR : ${PROJECT_BINARY_DIR}")
    message(STATUS "========================================================")
endfunction()

function(showPathInfos)
    message(STATUS "CMAKE_CURRENT_SOURCE_DIR : ${CMAKE_CURRENT_SOURCE_DIR}")
    message(STATUS "CMAKE_CURRENT_BINARY_DIR : ${CMAKE_CURRENT_BINARY_DIR}")
    message(STATUS "CMAKE_CURRENT_LIST_FILE : ${CMAKE_CURRENT_LIST_FILE}")
    message(STATUS "CMAKE_CURRENT_LIST_DIR : ${CMAKE_CURRENT_LIST_DIR}")
    message(STATUS "CMAKE_CURRENT_LIST_LINE : ${CMAKE_CURRENT_LIST_LINE}")
    message(STATUS "========================================================")
    message(STATUS "")
endfunction()